name: Auto Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      USER_NAME:
        description: 'Name of your GitHub Account'
        required: true
        default: 'YZBruh'
      USER_EMAIL:
        description: 'E-mail of your GitHub Account'
        required: true
        default: 'yagizzengin73@gmail.com'
      FIRMWARE_URL:
        description: 'Stock ROM Link'
        required: true
        default: ''
      GENERATE_VENDOR:
        description: 'Create Vendor Tree'
        required: true
        default: 'false'
        type: boolean
      UPLOAD_LINEAGE_DT:
        description: 'Upload LineageOS tree'
        required: true
        default: 'false'
        type: boolean
      UPLOAD_TWRP_DT:
        description: 'Upload TWRP tree'
        required: true
        default: 'false'
        type: boolean

jobs:
  dump:
    name: Auto Firmware Dumper
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GTOKEN }}
      TWT: ${{ github.event.inputs.UPLOAD_TWRP_DT }}
      LOT: ${{ github.event.inputs.UPLOAD_LINEAGE_DT }}
      GVT: ${{ github.event.inputs.GENERATE_VENDOR }}
      FUR: ${{ github.event.inputs.FIRMWARE_URL }}
      UN: ${{ github.event.inputs.USER_NAME }}
      UEM: ${{ github.event.inputs.USER_EMAIL }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: rokibhasansagar/slimhub_actions@main
      - uses: sersoft-gmbh/setup-gh-cli-action@v2
        with:
          version: stable

      - name: Setting Up Environment
        run: |
          sudo chmod -R 755 *
          mkdir workdir
          bash scripts/full_setup.sh "$PWD/workdir"
        working-directory: ${{ github.workspace }}

      - name: Authorize Git And GitHub CLI
        run: |
          . scripts/common_functions.sh
          git_auth "${{ env.UN }}" "${{ env.UEM }}" "${{ env.GITHUB_TOKEN }}"
        working-directory: ${{ github.workspace }}

      - name: Create Dump
        run: |
          cd workdir/DumprX
          sudo bash dumper.sh "${{ env.FUR }}"
          sudo chown -R $USER:$USER out
          sudo chmod -R 755 out
        working-directory: ${{ github.workspace }}

      - name: Upload ROM Dump
        run: |
          . scripts/common_functions.sh
          ls $PWD/workdir/DumprX/out
          dump_props_to_env_file $PWD/workdir/DumprX/out
          . env
          cd workdir/DumprX/out

          lineageDir="lineage-device-tree"
          teamWinDir="twrp-device-tree"
          if [ -d $lineageDir ]; then cp -r $lineageDir ${{ github.workspace }}; fi
          if [ -d $teamWinDir ]; then cp -r $teamWinDir ${{ github.workspace }}; fi
          compress_files "$PWD"
          bash ${{ github.workspace }}/scripts/upload_to_repo.sh "$PWD" dump
        working-directory: ${{ github.workspace }}

      - name: Create And Upload Vendor Tree
        if: env.GVT == 'true'
        run: |
          . scripts/common_functions.sh
          . env
          cd workdir
          lineageDir="lineage-device-tree"
          mkdir -p android/device/$BRAND/$DEVICE
          if [ -d $lineageDir ]; then cp -r $lineageDir/* android/device/$BRAND/$DEVICE
          else error "Cannot find Lineage device tree! Dumper may not have created"
          cd android/device/$BRAND/$DEVICE && chmod 755 *.sh
          bash extract-files.sh ${{ github.workspace }}/DumprX/out
          cd ../../vendor/$BRAND/$DEVICE
          chmod -R 755 *
          bash ${{ github.workspace }}/scripts/upload_to_repo.sh "$PWD" vendor
          sudo rm -rf ${{ github.workspace }}/workdir
        working-directory: ${{ github.workspace }}

      - name: Upload LineageOS Device Tree
        if: env.LOT == 'true'
        run: |
          . env
          bash ${{ github.workspace }}/scripts/upload_to_repo.sh "$PWD/lineage-device-tree" lineage lineage_device
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      - name: Upload TWRP Device Tree
        if: env.TWT == 'true'
        run: |
          . env
          bash ${{ github.workspace }}/scripts/upload_to_repo.sh "$PWD/twrp-device-tree/$BRAND/$CODENAME" twrp recovery_device
        working-directory: ${{ github.workspace }}
        continue-on-error: true
